"""Behaviour-neutral proof that the JSON-backed COMPOSITE_ROLE_PERMISSIONS
matches the old hardcoded literal exactly, byte for byte in permission
content (order-independent). This is the "prove nothing changed" commit that
must land before _has_intersection's ~30 call sites are touched -- see the
module roadmap Wave A2.

Real catalog changes made after that migration (a permission genuinely added
or removed) are reflected here deliberately, with a note, rather than left to
silently fail this test -- it is a frozen-snapshot regression lock, not a
change-freeze. `parent` gained `family:overview_read` for the multi-school
family overview page (Phase 5 of the multi-school access plan).
"""

from app.core.dependencies import COMPOSITE_ROLE_PERMISSIONS

_OLD_LITERAL: dict[str, set[str]] = {
    "super_admin": {"*"},
    "school_admin": {
        "school:write",
        "school:read",
        "level:create",
        "level:manage",
        "level:read",
        "class:create",
        "class:edit",
        "class:update",
        "class:read",
        "class:assign_teacher",
        "user:create",
        "user:invite",
        "user:delete",
        "user:link",
        "user:view",
        "user:read",
        "user:profile_read",
        "user:profile_edit",
        "teacher:create",
        "teacher:read",
        "teacher:write",
        "parent:read",
        "report:view",
        "student:create",
        "student:read",
        "event:create",
        "event:read",
        "event:view",
        "event:edit",
        "event:patch",
        "event:delete",
        "event:clone",
        "event:propose",
        "event:submit",
        "event:review",
        "event:publish",
        "event:view_draft",
        "event:archive",
        "event:audience_edit",
        "event:audience_predict",
        "resource:create",
        "resource:view",
        "resource:read",
        "resource:edit",
        "resource:update",
        "resource:delete",
        "resource:price",
        "resource:set_cost",
        "resource_type:create",
        "resource_type:read",
        "enrollment:teacher_approve",
        "enrollment:cancel",
        "enrollment:view_roster",
        "enrollment:read",
        "billing:audit",
        "billing:invoice",
        "billing:view_payment",
        "subsidy:manage",
        "audit:view",
        "health:view",
        "health:manage",
        "safety:manage",
        "announcement:manage",
        "notification:send",
        "notification:read",
        "notification:mark_read",
        "feedback:view",
    },
    "admin": {
        "school:write",
        "school:read",
        "level:create",
        "level:manage",
        "level:read",
        "class:create",
        "class:edit",
        "class:update",
        "class:read",
        "class:assign_teacher",
        "user:create",
        "user:invite",
        "user:delete",
        "user:link",
        "user:view",
        "user:read",
        "user:profile_read",
        "user:profile_edit",
        "teacher:create",
        "teacher:read",
        "teacher:write",
        "parent:read",
        "report:view",
        "student:create",
        "student:read",
        "event:create",
        "event:read",
        "event:view",
        "event:edit",
        "event:patch",
        "event:delete",
        "event:clone",
        "event:propose",
        "event:submit",
        "event:review",
        "event:publish",
        "event:view_draft",
        "event:archive",
        "event:audience_edit",
        "event:audience_predict",
        "resource:create",
        "resource:view",
        "resource:read",
        "resource:edit",
        "resource:update",
        "resource:delete",
        "resource:price",
        "resource:set_cost",
        "resource_type:create",
        "resource_type:read",
        "enrollment:teacher_approve",
        "enrollment:cancel",
        "enrollment:view_roster",
        "enrollment:read",
        "billing:audit",
        "billing:invoice",
        "billing:view_payment",
        "subsidy:manage",
        "audit:view",
        "health:view",
        "health:manage",
        "safety:manage",
        "announcement:manage",
        "notification:send",
        "notification:read",
        "notification:mark_read",
        "feedback:view",
    },
    "manager": {
        "school:read",
        "level:read",
        "level:create",
        "level:manage",
        "class:read",
        "class:create",
        "class:update",
        "class:edit",
        "class:assign_teacher",
        "user:create",
        "teacher:read",
        "parent:read",
        "student:read",
        "user:view",
        "user:read",
        "user:profile_read",
        "user:profile_edit",
        "event:read",
        "event:view",
        "event:review",
        "event:publish",
        "event:view_draft",
        "event:audience_predict",
        "resource:view",
        "resource:read",
        "resource:price",
        "resource:set_cost",
        "resource_type:read",
        "billing:invoice",
        "billing:pay",
        "billing:refund",
        "billing:audit",
        "billing:view_payment",
        "subsidy:manage",
        "enrollment:view_roster",
        "enrollment:read",
        "announcement:manage",
        "notification:send",
        "notification:read",
        "notification:mark_read",
        "feedback:view",
    },
    "teacher": {
        "school:read",
        "level:read",
        "class:read",
        "teacher:read",
        "student:read",
        "user:view",
        "user:read",
        "user:profile_read",
        "user:profile_edit",
        "event:create",
        "event:read",
        "event:view",
        "event:edit",
        "event:patch",
        "event:delete",
        "event:clone",
        "event:propose",
        "event:submit",
        "event:view_draft",
        "event:audience_edit",
        "event:audience_predict",
        "resource:create",
        "resource:view",
        "resource:read",
        "resource:edit",
        "resource:update",
        "resource:delete",
        "resource_type:create",
        "resource_type:read",
        "enrollment:teacher_approve",
        "enrollment:view_roster",
        "enrollment:read",
        "health:view",
        "health:manage",
        "notification:read",
        "notification:mark_read",
        "feedback:view",
        "feedback:create",
    },
    "parent": {
        "school:read",
        "user:profile_read",
        "user:profile_edit",
        "student:view_linked",
        "event:read",
        "event:view",
        "enrollment:parent_approve",
        "enrollment:cancel",
        "enrollment:read",
        "billing:pay",
        "billing:view_payment",
        "health:manage_child",
        "notification:read",
        "notification:mark_read",
        "feedback:create",
        "family:overview_read",
    },
    "student": {
        "school:read",
        "user:profile_read",
        "user:profile_edit",
        "event:read",
        "event:view",
        "enrollment:request",
        "enrollment:read",
        "notification:read",
        "notification:mark_read",
        "feedback:create",
    },
}


def test_json_backed_catalog_matches_old_literal_exactly():
    assert set(COMPOSITE_ROLE_PERMISSIONS.keys()) == set(_OLD_LITERAL.keys())
    for role in _OLD_LITERAL:
        assert COMPOSITE_ROLE_PERMISSIONS[role] == _OLD_LITERAL[role], (
            f"role={role} diverged: "
            f"missing={_OLD_LITERAL[role] - COMPOSITE_ROLE_PERMISSIONS[role]} "
            f"extra={COMPOSITE_ROLE_PERMISSIONS[role] - _OLD_LITERAL[role]}"
        )
